[package]
name = "ver5"
version = "0.1.0"
authors = ["Miro Svrtan <miro@mirosvrtan.me>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
tokio-timer = "*"

[lib]
name = "ver5"